"use strict";
const DATA="./data/us_bases_with_coords.csv";
const route=(coords)=>({type:"FeatureCollection",features:[{type:"Feature",properties:{},geometry:{type:"LineString",coordinates:coords}}]});
const geo={
 regular:route([[52.1,26.3],[57,25.7],[60.7,23.8],[80.6,2.4],[96.6,7.3],[106.1,-1.4],[107.7,7],[124.4,22.7],[128.4,29.3],[136.5,34.5]]),
 detour:route([[52.5,26.7],[56.6,26.3],[78.7,1.1],[114.8,-12.9],[116.7,-4.2],[121.5,4.4],[132.4,7.3],[134.2,31.4],[136.5,34.5]]),
 warning:{type:"FeatureCollection",features:[{type:"Feature",properties:{},geometry:{type:"Point",coordinates:[121,23.5]}}]}
};
const slides=[
 [["CHAPTER 01 · 日本へ向かう海路","CHAPTER 01 · THE SEA ROAD TO JAPAN"],["石油を運ぶ、一本の長い航路","A long route carrying Japan's oil"],["日本が消費する石油の約9割は、中東から海上輸送で運ばれます。ペルシャ湾を出たタンカーは、ホルムズ海峡、インド洋、マラッカ海峡、台湾海峡を経て日本へ向かいます。","About 90% of Japan's oil is transported by sea from the Middle East. Tankers travel through Hormuz, the Indian Ocean, Malacca and the Taiwan Strait."],[["約90%","中東に依存する原油輸入","of crude oil imports rely on the Middle East"],["10,000km+","日本まで続く海上輸送","of maritime transport to Japan"]],{center:[94,18],zoom:2.35,pitch:0,bearing:0},{regular:1,detour:0,warning:0,bases:0}],
 [["CHAPTER 02 · チョークポイント","CHAPTER 02 · CHOKEPOINT"],["狭い海峡に集中するタンカー","Tankers converge on a narrow strait"],["台湾海峡は幅約180kmの水路です。地理的に狭く、迂回には大きな追加距離が必要なため、日本のエネルギー輸送における重要な通過点です。","The Taiwan Strait is roughly 180 km wide. Its narrow geography and costly detours make it a critical chokepoint for Japan's energy transport."],[["約180km","台湾海峡の幅","approximate width"],["要衝","東アジア海運の通過点","a key shipping passage"]],{center:[121,23.5],zoom:5.4,pitch:12,bearing:0},{regular:1,detour:0,warning:0,bases:0}],
 [["CHAPTER 03 · 緊張が高まるとき","CHAPTER 03 · WHEN TENSIONS RISE"],["航行の安全が揺らぐリスク","A risk to safe navigation"],["軍事的な緊張が高まれば、タンカーの安全な航行が難しくなる可能性があります。海峡の封鎖や通行制限は、日本への石油輸送に直接影響します。","Military tensions could make tanker navigation difficult. A blockade or restrictions would directly affect oil shipments to Japan."],[["直接影響","日本への石油輸送","to shipments bound for Japan"],["高リスク","海峡封鎖・通行制限","blockade or restrictions"]],{center:[121,23.5],zoom:5.7,pitch:30,bearing:-10},{regular:1,detour:0,warning:1,bases:0}],
 [["CHAPTER 04 · 日本国内の拠点","CHAPTER 04 · BASES IN JAPAN"],["周辺の軍事活動と、民間航路","Military activity and civilian shipping"],["日本国内と周辺には複数の米軍施設があります。有事には基地周辺で軍事活動が活発化し、民間船舶の航行環境がさらに複雑になることが想定されます。","U.S. military facilities are located across Japan. In a crisis, increased military activity could make civilian shipping conditions more complex."],[["75地点","地図上で確認できる施設・区域","facilities and areas mapped"],["76件","収録データ（座標欠損1件を含む）","records, including one without coordinates"]],{center:[137,35],zoom:4.2,pitch:32,bearing:-13},{regular:0,detour:0,warning:0,bases:1}],
 [["CHAPTER 05 · 迂回という選択","CHAPTER 05 · THE DETOUR OPTION"],["安全と引き換えに延びる距離","More distance in exchange for safety"],["台湾海峡を避ける航路は、フィリピン東側やロンボク海峡、マカッサル海峡を経由します。通常航路より距離が増え、航海日数と輸送費も上昇します。","A route avoiding the Taiwan Strait can pass east of the Philippines through Lombok and Makassar, increasing distance, time and cost."],[["+30–40%","航行距離の増加","increase in distance"],["+2–4日","追加の航海日数","additional sailing days"]],{center:[100,12],zoom:2.45,pitch:0,bearing:0},{regular:0,detour:1,warning:0,bases:0}],
 [["CHAPTER 06 · 二つの航路","CHAPTER 06 · TWO ROUTES"],["距離と時間の差を比べる","Compare the distance and time gap"],["通常航路と迂回航路を重ねると、距離差が見えてきます。迂回はリスクを下げる可能性がある一方、追加の燃料と運賃を伴います。","Overlaying both routes makes the distance gap visible. A detour may reduce risk but requires more fuel and raises freight costs."],[["緑","通常航路","regular route","route-regular"],["青","迂回航路","detour route","route-detour"]],{center:[100,12],zoom:2.45,pitch:0,bearing:0},{regular:1,detour:1,warning:0,bases:0}],
 [["CHAPTER 07 · エネルギー安全保障","CHAPTER 07 · ENERGY SECURITY"],["海の向こうの緊張は、暮らしにつながる","Distant tensions reach everyday life"],["台湾海峡をめぐる問題は、軍事・外交だけではありません。石油輸送ルートの変化は、燃料価格、物流、産業活動、そして日常生活へ波及する可能性があります。","The Taiwan Strait is not only a military issue. Changes to oil routes can affect fuel prices, logistics, industry and daily life."],[["海運","日本のエネルギーを支える基盤","foundation of energy supply"],["選択","安全性とコストの均衡","balancing safety and cost"]],{center:[123.5,24.5],zoom:3.25,pitch:10,bearing:0},{regular:1,detour:1,warning:1,bases:0}],
 [["CHAPTER 08 · 社会への波及","CHAPTER 08 · IMPACT ON SOCIETY"],["原油高は、暮らしへどう届くのか","How higher oil prices reach daily life"],["原油価格の上昇は、石油製品だけでなく、電気、輸送、食料品、幅広いサービスへ時間差を伴って波及します。輸入に頼る日本では海外への所得流出が増え、家計の実質所得と企業収益、経済成長を圧迫します。","Higher oil prices spread beyond petroleum products to electricity, transport, food and services over time. For import-dependent Japan, the resulting income outflow weighs on household purchasing power, corporate profits and growth."],[["直後","石油製品・基礎素材","petroleum and basic materials"],["3〜6か月","電気・輸送・加工品","electricity, transport and processed goods"],["1年程度","最終財・サービス","final goods and services"]],{center:[117,26],zoom:3.1,pitch:15,bearing:0},{regular:1,detour:1,warning:1,bases:0},{
   flow:{ja:["原油輸入価格","石油製品・原材料","電気・輸送","商品・サービス","家計・景気"],en:["Crude import prices","Petroleum and materials","Electricity and transport","Goods and services","Households and growth"]},
   impacts:[
    {title:["家計","Households"],stat:"電気 +31.4%",copy:["ガソリン、電気、商品価格が上がり、実質所得と消費余力を圧迫。","Higher energy and goods prices reduce real income and purchasing power."]},
    {title:["物流","Logistics"],stat:"道路 +4.0% / 航空 +12.8%",copy:["燃料費と運賃が上昇し、商品価格や事業継続へ波及。","Fuel and freight costs rise, affecting prices and business continuity."]},
    {title:["企業","Businesses"],stat:"石油製品 +58.1%",copy:["原材料・エネルギー費が増え、利益、賃上げ、投資を圧迫。","Input and energy costs squeeze profits, wages and investment."]},
    {title:["物価","Prices"],stat:"飲食料品 +3.1%",copy:["川上の値上げが財からサービスへ広がり、消費者物価を押し上げ。","Upstream costs spread from goods to services and consumer prices."]},
    {title:["景気","Growth"],stat:"実質所得 ↓",copy:["海外への所得流出が増え、個人消費と経済成長を下押し。","Income flows overseas, weighing on consumption and economic growth."]}
   ],
   source:["出典：日本銀行「経済・物価情勢の展望（2026年4月）」図表B2-1","Source: Bank of Japan, Outlook for Economic Activity and Prices, April 2026, Chart B2-1"],
   note:["数値は「石炭・原油・天然ガス」部門の価格が100%上昇した場合の産業連関に基づく試算であり、予測ではありません。実際の影響は為替、補助政策、企業の価格転嫁によって変わります。","Figures are input-output estimates for a 100% price increase in coal, crude oil and natural gas, not forecasts. Actual effects vary with exchange rates, subsidies and firms' price pass-through."]
  }]
];
const T={
 ja:{explore:"基地を探す",database:"DATABASE",basesTitle:"在日米軍施設",searchLabel:"施設名を検索",placeholder:"例：横田、嘉手納",prefecture:"都道府県",purpose:"用途",all:"すべて",results:"件の施設",reset:"条件を解除",loadError:"施設データを読み込めませんでした。",retry:"再読み込み",layers:"表示",regularRoute:"通常航路",detourRoute:"迂回航路",riskZone:"台湾海峡リスク",bases:"米軍施設",sources:"出典",sourceText:"施設データ：e-Stat「在日米軍施設・区域の状況」。航路は説明用の概略図です。",sourceBojOutlook:"日本銀行「経済・物価情勢の展望（2026年4月）」図表B2-1 ↗",sourceBojSpeech:"日本銀行「最近の経済・物価情勢と金融政策運営」↗",sourceEnergyWhitepaper:"資源エネルギー庁「エネルギー白書2024」↗",sourceMlitWhitepaper:"国土交通省「国土交通白書」燃料価格上昇に伴う輸送費用の増大 ↗",location:"所在地",area:"面積",empty:"条件に一致する施設がありません。",selected:"を地図に表示しました",prev:"前の場面",next:"次の場面",close:"閉じる"},
 en:{explore:"Explore bases",database:"DATABASE",basesTitle:"U.S. Military Facilities",searchLabel:"Search by facility name",placeholder:"e.g. Yokota, Kadena",prefecture:"Prefecture",purpose:"Purpose",all:"All",results:"facilities",reset:"Clear filters",loadError:"Facility data could not be loaded.",retry:"Reload",layers:"Layers",regularRoute:"Regular route",detourRoute:"Detour route",riskZone:"Taiwan Strait risk",bases:"U.S. facilities",sources:"Sources",sourceText:"Facility data: e-Stat. Routes are schematic.",sourceBojOutlook:"Bank of Japan, Outlook for Economic Activity and Prices (April 2026), Chart B2-1 ↗",sourceBojSpeech:"Bank of Japan, Recent Economic and Price Developments and Monetary Policy ↗",sourceEnergyWhitepaper:"Agency for Natural Resources and Energy, Energy White Paper 2024 ↗",sourceMlitWhitepaper:"Ministry of Land, Infrastructure, Transport and Tourism, White Paper on fuel and transport costs ↗",location:"Location",area:"Area",empty:"No facilities match these filters.",selected:"shown on the map",prev:"Previous chapter",next:"Next chapter",close:"Close"}
};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const E={story:$("#story"),k:$("#kicker"),title:$("#title"),copy:$("#copy"),facts:$("#facts"),impactFlow:$("#impact-flow"),impactCards:$("#impact-cards"),slideSource:$("#slide-source"),chapter:$("#chapter"),progress:$("#progress"),dots:$("#dots"),prev:$("#prev"),next:$("#next"),panel:$("#explore"),search:$("#search"),pref:$("#prefecture"),purpose:$("#purpose"),results:$("#results"),count:$("#count"),error:$("#error"),detail:$("#detail"),detailName:$("#detail-name"),detailList:$("#detail-list"),legend:$("#legend"),toast:$("#toast")};
const state={lang:"ja",slide:0,bases:[],filtered:[],ready:false,layers:{regular:1,detour:0,warning:0,bases:0}};
const map=new maplibregl.Map({container:"map",style:"https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json",center:slides[0][4].center,zoom:slides[0][4].zoom,attributionControl:false});
map.addControl(new maplibregl.NavigationControl({showCompass:false}),"bottom-right");map.addControl(new maplibregl.AttributionControl({compact:true}),"bottom-left");
const feature=b=>({type:"Feature",geometry:{type:"Point",coordinates:[b.lon,b.lat]},properties:{id:b.id}});
function line(id,source,color,width,opacity=.92,before){map.addLayer({id,type:"line",source,layout:{"line-join":"round","line-cap":"round"},paint:{"line-color":color,"line-width":width,"line-opacity":opacity}},before)}
function setupMap(){map.addSource("regular",{type:"geojson",data:geo.regular});map.addSource("detour",{type:"geojson",data:geo.detour});map.addSource("warning",{type:"geojson",data:geo.warning});map.addSource("bases",{type:"geojson",data:{type:"FeatureCollection",features:state.bases.map(feature)}});
 line("regular-line","regular","#55d17d",5);line("regular-glow","regular","#55d17d",12,.16,"regular-line");line("detour-line","detour","#41b9d5",5);line("detour-glow","detour","#41b9d5",12,.16,"detour-line");
 map.addLayer({id:"warning-layer",type:"circle",source:"warning",paint:{"circle-radius":["interpolate",["linear"],["zoom"],2,36,6,180,8,260],"circle-color":"#eb5a55","circle-opacity":.2,"circle-stroke-color":"#eb5a55","circle-stroke-width":2}});
 map.addLayer({id:"bases-layer",type:"circle",source:"bases",paint:{"circle-radius":["interpolate",["linear"],["zoom"],3,4,9,8],"circle-color":"#7ac7a6","circle-stroke-color":"#0d1713","circle-stroke-width":1.5}});
 map.on("click","bases-layer",e=>{const b=state.bases.find(x=>x.id===e.features[0].properties.id);if(b)selectBase(b,false)});map.on("mouseenter","bases-layer",()=>map.getCanvas().style.cursor="pointer");map.on("mouseleave","bases-layer",()=>map.getCanvas().style.cursor="");state.ready=true;applySlide(0,false)}
function parse(row,i){const lat=parseFloat(row.latitude),lon=parseFloat(row.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return null;const locations=Array.from({length:7},(_,n)=>row[`所在地${n+1}`]).filter(v=>v&&v!=="-");const match=(locations[0]||"").match(/^(北海道|東京都|京都府|大阪府|.{2,3}県)/);return{id:`b${i}`,name:row["施設・区域名"]||"名称不明",purpose:row["用途"]||"-",locations,pref:match?match[1]:"その他",area:row["2-1(a)面積（千㎡）"]||"-",lat,lon}}
function load(){E.error.hidden=true;Papa.parse(DATA,{download:true,header:true,skipEmptyLines:true,complete:r=>{state.bases=r.data.map(parse).filter(Boolean);state.filtered=[...state.bases];filters();renderResults();if(state.ready)map.getSource("bases").setData({type:"FeatureCollection",features:state.bases.map(feature)})},error:()=>{state.bases=[];state.filtered=[];renderResults();E.error.hidden=false}})}
function fill(select,values){const chosen=select.value;select.replaceChildren();const all=document.createElement("option");all.value="";all.textContent=T[state.lang].all;select.append(all);values.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;select.append(o)});if(values.includes(chosen))select.value=chosen}
function filters(){fill(E.pref,[...new Set(state.bases.map(b=>b.pref))].sort());fill(E.purpose,[...new Set(state.bases.map(b=>b.purpose))].sort())}
function filter(){const q=E.search.value.trim().toLocaleLowerCase("ja");state.filtered=state.bases.filter(b=>(!q||[b.name,b.purpose,...b.locations].join(" ").toLocaleLowerCase("ja").includes(q))&&(!E.pref.value||b.pref===E.pref.value)&&(!E.purpose.value||b.purpose===E.purpose.value));renderResults()}
function renderResults(){E.count.textContent=state.filtered.length;E.results.replaceChildren();if(!state.filtered.length&&state.bases.length){const p=document.createElement("p");p.className="error";p.textContent=T[state.lang].empty;E.results.append(p);return}state.filtered.forEach(b=>{const btn=document.createElement("button");btn.className="result";const text=document.createElement("span"),name=document.createElement("strong"),meta=document.createElement("span"),arrow=document.createElement("b");name.textContent=b.name;meta.textContent=`${b.pref} · ${b.purpose}`;arrow.textContent="→";text.append(name,meta);btn.append(text,arrow);btn.onclick=()=>selectBase(b,true);E.results.append(btn)})}
function detailRow(a,b){const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=a;dd.textContent=b;E.detailList.append(dt,dd)}
function selectBase(b,close){setLayer("bases",1);map.flyTo({center:[b.lon,b.lat],zoom:10.5,pitch:35,speed:.8,essential:true});E.detailName.textContent=b.name;E.detailList.replaceChildren();detailRow(T[state.lang].purpose,b.purpose);detailRow(T[state.lang].location,b.locations.join(" / ")||"-");detailRow(T[state.lang].area,b.area==="-"?"-":`${b.area} 千㎡`);E.detail.classList.add("is-open");E.detail.ariaHidden="false";if(close&&innerWidth<=760)closeExplore();toast(`${b.name} ${T[state.lang].selected}`)}
const ids={regular:["regular-glow","regular-line"],detour:["detour-glow","detour-line"],warning:["warning-layer"],bases:["bases-layer"]};
function setLayer(name,on){state.layers[name]=+on;if(state.ready)ids[name].forEach(id=>map.getLayer(id)&&map.setLayoutProperty(id,"visibility",on?"visible":"none"));$$("[data-layer]").forEach(i=>i.checked=!!state.layers[i.dataset.layer])}
function renderImpact(extra,l){const active=Boolean(extra);E.story.classList.toggle("is-impact",active);E.impactFlow.hidden=!active;E.impactCards.hidden=!active;E.slideSource.hidden=!active;E.impactFlow.replaceChildren();E.impactCards.replaceChildren();E.slideSource.replaceChildren();if(!active)return;extra.flow[state.lang].forEach((label,i)=>{const item=document.createElement("span");item.textContent=label;E.impactFlow.append(item);if(i<extra.flow[state.lang].length-1){const arrow=document.createElement("b");arrow.textContent="→";E.impactFlow.append(arrow)}});extra.impacts.forEach(impact=>{const card=document.createElement("article"),title=document.createElement("h3"),stat=document.createElement("strong"),copy=document.createElement("p");card.className="impact-card";title.textContent=impact.title[l];stat.textContent=impact.stat;copy.textContent=impact.copy[l];card.append(title,stat,copy);E.impactCards.append(card)});const link=document.createElement("a"),note=document.createElement("p");link.href="https://www.boj.or.jp/mopo/outlook/gor2604b.pdf";link.target="_blank";link.rel="noreferrer";link.textContent=`${extra.source[l]} ↗`;note.textContent=extra.note[l];E.slideSource.append(link,note)}
function renderSlide(){const s=slides[state.slide],l=state.lang==="ja"?0:1;E.k.textContent=s[0][l];E.title.textContent=s[1][l];E.copy.textContent=s[2][l];E.chapter.textContent=`${String(state.slide+1).padStart(2,"0")} / ${String(slides.length).padStart(2,"0")}`;E.progress.style.width=`${(state.slide+1)/slides.length*100}%`;E.prev.disabled=state.slide===0;E.next.disabled=state.slide===slides.length-1;E.facts.replaceChildren();s[3].forEach(f=>{const d=document.createElement("div"),v=document.createElement("strong"),t=document.createElement("span");d.className="fact";if(f[3])d.classList.add(f[3]);v.textContent=f[0];t.textContent=f[l+1];d.append(v,t);E.facts.append(d)});renderImpact(s[6],l);[...E.dots.children].forEach((d,i)=>{d.classList.toggle("is-active",i===state.slide);d.setAttribute("aria-current",i===state.slide?"step":"false")})}
function applySlide(i,animate=true){state.slide=Math.max(0,Math.min(slides.length-1,i));state.layers={...slides[state.slide][5]};renderSlide();Object.entries(state.layers).forEach(([k,v])=>setLayer(k,v));if(state.ready)map[animate?"flyTo":"jumpTo"]({...slides[state.slide][4],speed:.65,curve:1.3,essential:true})}
function setLang(lang){state.lang=lang;document.documentElement.lang=lang;$$("[data-t]").forEach(n=>n.textContent=T[lang][n.dataset.t]);$$("[data-lang]").forEach(b=>{const on=b.dataset.lang===lang;b.classList.toggle("is-active",on);b.ariaPressed=on});E.search.placeholder=T[lang].placeholder;E.prev.ariaLabel=T[lang].prev;E.next.ariaLabel=T[lang].next;filters();renderSlide();renderResults();[...E.dots.children].forEach((d,i)=>d.ariaLabel=`${i+1}: ${slides[i][1][lang==="ja"?0:1]}`)}
function openExplore(){E.panel.classList.add("is-open");E.panel.ariaHidden="false";$("#explore-open").ariaExpanded="true";setTimeout(()=>E.search.focus(),260)}function closeExplore(){E.panel.classList.remove("is-open");E.panel.ariaHidden="true";$("#explore-open").ariaExpanded="false"}
let timer;function toast(text){clearTimeout(timer);E.toast.textContent=text;E.toast.classList.add("show");timer=setTimeout(()=>E.toast.classList.remove("show"),2200)}
slides.forEach((s,i)=>{const b=document.createElement("button");b.ariaLabel=`${i+1}: ${s[1][0]}`;b.onclick=()=>applySlide(i);E.dots.append(b)});
E.prev.onclick=()=>applySlide(state.slide-1);E.next.onclick=()=>applySlide(state.slide+1);$("#explore-open").onclick=openExplore;$("#explore-close").onclick=closeExplore;E.search.oninput=filter;E.pref.onchange=filter;E.purpose.onchange=filter;$("#reset").onclick=()=>{E.search.value="";E.pref.value="";E.purpose.value="";filter()};$("#retry").onclick=load;$("#detail-close").onclick=()=>{E.detail.classList.remove("is-open");E.detail.ariaHidden="true"};$("#layers-open").onclick=()=>{E.legend.hidden=!E.legend.hidden;$("#layers-open").ariaExpanded=!E.legend.hidden};$("#source-open").onclick=()=>$("#source-box").hidden=!$("#source-box").hidden;$$("[data-layer]").forEach(i=>i.onchange=()=>setLayer(i.dataset.layer,i.checked));$$("[data-lang]").forEach(b=>b.onclick=()=>setLang(b.dataset.lang));document.addEventListener("keydown",e=>{if(e.target.matches("input,select,button"))return;if(e.key==="ArrowLeft")applySlide(state.slide-1);if(e.key==="ArrowRight")applySlide(state.slide+1);if(e.key==="Escape"){closeExplore();E.detail.classList.remove("is-open")}});
renderSlide();load();map.on("load",setupMap);map.on("error",e=>e.error&&console.error("MapLibre:",e.error));
